[package]
name = "ribbon_count"
version = "0.1.0"
edition = "2018"
authors = ["Virgil Pierce <virgilpierce@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



